// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfq5F4tM_NDBax_-gTbvS6WZkoHCrZt5Q',
    appId: '1:489750405560:web:08e0b26af9a9c9ed87ef4d',
    messagingSenderId: '489750405560',
    projectId: 'flower-app-b0514',
    authDomain: 'flower-app-b0514.firebaseapp.com',
    storageBucket: 'flower-app-b0514.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGWT0MQwCcVET6ESdF41nkGwEyeiaL4k',
    appId: '1:489750405560:android:731ded579ee449ad87ef4d',
    messagingSenderId: '489750405560',
    projectId: 'flower-app-b0514',
    storageBucket: 'flower-app-b0514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN1LcbTUF_wBrDFtdGsuadFakiRdWm9Gg',
    appId: '1:489750405560:ios:b7e77c4706dbb69887ef4d',
    messagingSenderId: '489750405560',
    projectId: 'flower-app-b0514',
    storageBucket: 'flower-app-b0514.firebasestorage.app',
    iosBundleId: 'com.example.floristaEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN1LcbTUF_wBrDFtdGsuadFakiRdWm9Gg',
    appId: '1:489750405560:ios:b7e77c4706dbb69887ef4d',
    messagingSenderId: '489750405560',
    projectId: 'flower-app-b0514',
    storageBucket: 'flower-app-b0514.firebasestorage.app',
    iosBundleId: 'com.example.floristaEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfq5F4tM_NDBax_-gTbvS6WZkoHCrZt5Q',
    appId: '1:489750405560:web:c888be3a191cd38387ef4d',
    messagingSenderId: '489750405560',
    projectId: 'flower-app-b0514',
    authDomain: 'flower-app-b0514.firebaseapp.com',
    storageBucket: 'flower-app-b0514.firebasestorage.app',
  );
}
